import {Inter} from "next/font/google";
import '@mantine/core/styles.css';
import {ColorSchemeScript} from "@mantine/core";
import Providers from "@/app/components/Providers";
import {Metadata} from "next";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "AIESEC One App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
    <head>
      <ColorSchemeScript/><title>AIESEC One</title>
    </head>
    <body className={inter.className}>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  );
}
