import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";
import Providers from "@/app/components/Providers";
import MainAppShell from "@/app/components/MainAppShell";
import { Metadata } from "next";
import { Suspense } from "react";
import Loading from "@/app/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AIESEC One App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <title>AIESEC One</title>
      </head>

      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Providers>
            <MainAppShell>{children}</MainAppShell>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
